config/routes.rb
Rails.application.routes.draw do
  resources :owners, :dogs
  resources :users, only: [:new, :create]
  get 'welcome', to: 'sessions#welcome'
  root  "sessions#welcome"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'authorized', to: 'sessions#page_requires_login'
  delete 'owners/:id/delete' => 'owners#destroy', as: 'owners_delete'
  get '/owners/:id/delete' => 'owners#destroy'
  get '/search/:input' => 'dogs#search'
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :owner
end

app/models/owner.rb
class Owner < ApplicationRecord
    has_many :dogs, dependent: :delete_all
  
    def to_s
      "#{first_name} #{last_name}"
    end
  end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?
    def current_user
        User.find_by(id: session[:user_id])
    end
    def logged_in?
           
        !current_user.nil?
    end
    def authorized
       redirect_to '/welcome' unless logged_in?
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :current_dog, only: [:show, :edit, :update, :destroy]

  def index
    @dogs = Dog.all
  end

  def show

  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.create(dog_params)

    redirect_to dog_path(@dog)
  end

  def edit

  end

  def update
    @dog.update(dog_params)

    redirect_to dog_path(@dog)
  end

  def destroy
    @dog.destroy

    redirect_to dogs_path
  end

  def search 
    @key = dogs.all
    render "dogs/search"

  end

  private
  def dog_params
    params.require(:dog).permit(:name, :breed, :age, :owner_id)
  end

  def current_dog
    @dog = Dog.find(params[:id])
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :current_owner, only: [:show, :edit, :update, :destroy]

  def index
    @owners = Owner.all
  end

  def show

  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.create(owner_params)

    redirect_to owner_path(@owner)
  end

  def edit

  end

  def update
    @owner.update(owner_params)

    redirect_to owner_path(@owner)
  end

  def destroy
    @owner.destroy

    redirect_to owners_path
  end

  

  private
  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :occupation, :age, :img_url)
  end

  def current_owner
    @owner = Owner.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create, :welcome]
  
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id 
        redirect_to '/welcome'
    end
  end

  def welcome
    
  end

  def login
  end

  def page_requires_login
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def 

  def create
    @user = User.create(params.require(:user).permit(:username,        
    :password))
    session[:user_id] = @user.id
    redirect_to '/welcome'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dogs/edit.html.erb
<h3>Edit Dog</h3>
<%= form_with model: @dog do |form| %>
  <p>Name: <%= form.text_field :name %></p>
  <p>Breed: <%= form.text_field :breed %></p>
  <p>Age: <%= form.number_field :age %></p>

  <p>Owner: <%= form.select :owner_id, Owner.all.map { |owner| [ owner.to_s, owner.id ] } %></p>
  <%= form.submit %>
<% end %>

app/views/dogs/index.html.erb
<table>
  <% @dogs.each do |dog| %>
    <br>
    <tr>
      <td><%= link_to dog.name, dog_path(dog) %></td>
      <td><%= button_to 'Edit', edit_dog_path(dog), method: 'get'%></td>
      <td><%= button_to 'Remove', dog_path(dog), method: 'delete'%></td>
    <% end %>
</table>

app/views/dogs/new.html.erb
<h3>Add Dog</h3>
<%= form_with model: @dog do |form| %>
  <p>Name: <%= form.text_field :name %></p>
  <p>Breed: <%= form.text_field :breed %></p>
  <p>Age: <%= form.number_field :age %></p>

  <p>Owner: <%= form.select :owner_id, Owner.all.map { |owner| [ owner.to_s, owner.id ] } %></p>
  <%= form.submit %>
<% end %>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>
<%= link_to 'Edit', edit_dog_path(@dog) %>
<p><b>Breed:</b> <%= @dog.breed %></p>
<p><b>Age:</b> <%= @dog.age %></p>

<h4>Owner: <%= link_to @dog.owner.to_s, owner_path(@dog.owner) %></h4>

<%= link_to "Delete", @dog, method: 'delete' %></p>
<p><%= link_to 'Go back to all dogs', dogs_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class= 'container'>
    <%= yield %>
  </div>
  </body>
</html>

app/views/owners/edit.html.erb
<h3>Edit Owner</h3>
<%= form_with model: @owner do |form| %>
  <p> First Name: <%= form.text_field :first_name %></p>
  <p>Last Name: <%= form.text_field :last_name %></p>
  <p>Occupation: <%= form.text_area :occupation %></p>
  <p>Image url: <%= form.text_field :img_url %></p>
  <p>Age: <%= form.number_field :age %></p>

  <%= form.submit %>
<% end %>

app/views/owners/index.html.erb
<table>
  <% @owners.each do |owner| %>
    <br>
    <tr>
      <td><%= link_to owner.to_s, owner_path(owner) %></td>
     
      <td><%= button_to 'Remove', owner_path(owner), method: 'delete'%></td>
    <% end %>
</table>



<img src="https://img.etsystatic.com/il/8daee8/1445300227/il_340x270.1445300227_mitp.jpg?version=0">

app/views/owners/new.html.erb
<h3>Add Owner</h3>
<%= form_with model: @owner do |form| %>
  <p> First Name: <%= form.text_field :first_name %></p>
  <p>Last Name: <%= form.text_field :last_name %></p>
  <p>Occupation: <%= form.text_area :occupation %></p>
  <p>Image url: <%= form.text_field :img_url %></p>
  <p>Age: <%= form.number_field :age %></p>

  <%= form.submit %>
<% end %>

app/views/owners/show.html.erb
<h1><%= @owner.to_s %></h1>
<%= link_to 'Edit', edit_owner_path(@owner) %>
<p><b>Occupation:</b> <%= @owner.occupation %></p>
<p><b>Age:</b> <%= @owner.age %></p>

<img src="<%= @owner.img_url %>" alt="Owner_img_url">

<h3>Dogs</h3>
<ul>
  <% @owner.dogs.each do |dog| %>
  <li><%= link_to dog.name, dog_path(dog) %></li>
  <% end %>
</ul><br>


<p><%= link_to 'Go back to all owners', owners_path %></p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="/">Home</a>
        <a class="nav-link" href="/users/new">Signup</a>
        <a class="nav-link" href="/login">Login</a>
        <a class="nav-link" href="/owners">OwnersList</a>
        <a class="nav-link" href="/owners/new">AddOwners</a>
        <a class="nav-link" href="/dogs">Doglist</a>
        <a class="nav-link" href="/dogs/new">AddDog</a>
        <nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>
      </div>
    </div>
  </div>
</nav>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit %>
<%end%>